In [4]:
from pathlib import Path

RAW = Path("data/luad_raw")

files = list(RAW.glob("*"))

print(f"Found {len(files)} files:\n")
for f in files:
    print(f.name)

Found 5 files:

LUAD_proteomics_gene_abundance_log2_reference_intensity_normalized_Normal.txt
LUAD_proteomics_gene_abundance_log2_reference_intensity_normalized_Tumor.txt
LUAD_RNAseq_gene_RSEM_coding_UQ_1500_log2_Normal.txt
LUAD_RNAseq_gene_RSEM_coding_UQ_1500_log2_Tumor.txt
LUAD_somatic_mutation_gene_level_binary.txt

In [5]:
from pathlib import Path

RAW = Path("data/luad_raw")

files = list(RAW.glob("LUAD*"))

print(f"Found {len(files)} LUAD files:\n")
for f in files:
    print(f.name)

Found 5 LUAD files:

LUAD_proteomics_gene_abundance_log2_reference_intensity_normalized_Normal.txt
LUAD_proteomics_gene_abundance_log2_reference_intensity_normalized_Tumor.txt
LUAD_RNAseq_gene_RSEM_coding_UQ_1500_log2_Normal.txt
LUAD_RNAseq_gene_RSEM_coding_UQ_1500_log2_Tumor.txt
LUAD_somatic_mutation_gene_level_binary.txt

In [6]:
import pandas as pd

rna_tumor_file = next(RAW.glob("*RNAseq*Tumor.txt"))
rna_normal_file = next(RAW.glob("*RNAseq*Normal.txt"))

rna_tumor = pd.read_csv(rna_tumor_file, sep="\t")
rna_normal = pd.read_csv(rna_normal_file, sep="\t")

print("RNA Tumor shape:", rna_tumor.shape)
print("RNA Normal shape:", rna_normal.shape)

print("\nRNA Tumor first 5 rows:")
display(rna_tumor.head())

print("\nRNA Normal first 5 rows:")
display(rna_normal.head())

RNA Tumor shape: (60669, 111)
RNA Normal shape: (60669, 102)

RNA Tumor first 5 rows:

,idx,11LU013,11LU016,11LU022,11LU035,C3L-00001,C3L-00009,C3L-00080,C3L-00083,C3L-00093,...,C3N-02423,C3N-02424,C3N-02433,C3N-02529,C3N-02572,C3N-02582,C3N-02586,C3N-02587,C3N-02588,C3N-02729
0,ENSG00000000003.15,11.6916,11.1816,10.3317,10.4917,10.6017,10.3017,9.8517,8.7005,10.8891,...,10.3117,8.8517,9.9918,9.9318,10.0118,10.9517,10.1217,11.3017,11.4316,10.0318
1,ENSG00000000005.6,1.6363,1.3274,0.0000,0.0000,3.2138,2.2960,0.0000,0.0000,0.0000,...,1.8178,0.0000,0.0000,1.3334,1.8466,6.5649,1.8610,2.1403,1.2275,1.3214
2,ENSG00000000419.12,9.6320,9.7019,10.5117,9.4019,9.6616,9.5919,9.9717,8.1297,9.8994,...,9.3519,9.4217,9.2520,9.3620,9.6418,9.3620,9.1019,9.5019,9.4621,10.0718
3,ENSG00000000457.14,10.3418,9.9818,9.8818,9.7118,10.4117,9.9218,9.8317,9.7113,9.9693,...,9.7418,9.5317,10.3117,10.3417,10.4817,10.1318,10.3117,9.6118,9.9719,10.7117
4,ENSG00000000460.17,9.2921,9.5219,10.0018,9.0819,8.7213,8.7622,9.4616,7.1473,9.2496,...,9.1520,8.7817,8.4824,9.2021,9.1819,8.8922,8.1122,8.1923,9.5020,8.2626

RNA Normal first 5 rows:

,idx,C3L-00001,C3L-00009,C3L-00080,C3L-00083,C3L-00093,C3L-00094,C3L-00095,C3L-00140,C3L-00144,...,C3N-02423,C3N-02424,C3N-02433,C3N-02529,C3N-02572,C3N-02582,C3N-02586,C3N-02587,C3N-02588,C3N-02729
0,ENSG00000000003.15,10.3317,8.8895,9.8118,9.3715,9.4119,9.2820,8.9918,9.1119,9.2615,...,9.6918,9.1518,9.6619,9.9418,8.9916,9.7318,9.0518,9.5719,9.6517,9.5420
1,ENSG00000000005.6,2.9150,1.8232,2.1948,1.7595,3.4905,2.0865,0.0000,0.0000,2.1695,...,2.2261,1.5088,0.7889,2.7000,2.0770,2.4167,0.0000,2.8388,1.9491,0.7721
2,ENSG00000000419.12,9.3716,9.4694,9.6018,9.2914,9.3719,9.4519,9.3618,9.2818,9.2415,...,9.0518,9.2818,9.3620,9.2420,9.1616,9.3419,9.0618,9.1621,9.3418,9.1422
3,ENSG00000000457.14,10.1017,10.0793,9.6118,9.9316,9.6118,9.9218,9.3618,9.8218,9.8916,...,9.9517,9.8618,9.5420,9.8318,10.0017,10.0318,10.0917,9.9218,10.0017,9.9619
4,ENSG00000000460.17,8.0613,7.9599,8.1321,8.0408,7.9025,7.5530,7.6722,8.0422,7.7908,...,8.0721,8.1120,7.6534,8.1726,7.8613,8.1322,8.3120,8.1826,8.1919,8.0230

In [7]:
# Load proteomics and mutation files

prot_tumor_file = next(RAW.glob("*proteomics*Tumor.txt"))
prot_normal_file = next(RAW.glob("*proteomics*Normal.txt"))
mut_file = next(RAW.glob("*somatic_mutation*gene_level*"))

prot_tumor = pd.read_csv(prot_tumor_file, sep="\t")
prot_normal = pd.read_csv(prot_normal_file, sep="\t")
mutation = pd.read_csv(mut_file, sep="\t")

print("Protein Tumor shape:", prot_tumor.shape)
print("Protein Normal shape:", prot_normal.shape)
print("Mutation shape:", mutation.shape)

print("\nProtein Tumor:")
display(prot_tumor.head())

print("\nProtein Normal:")
display(prot_normal.head())

print("\nMutation:")
display(mutation.head())

Protein Tumor shape: (12433, 111)
Protein Normal shape: (12431, 102)
Mutation shape: (10881, 109)

Protein Tumor:

,idx,C3N-01799,C3L-01890,C3N-00572,C3N-02423,C3N-02729,C3L-00263,C3N-01410,C3N-00578,C3N-02587,...,C3N-00579,C3N-02582,C3L-02350,C3N-00738,C3N-00959,C3N-02003,C3N-00175,C3N-01823,C3L-02549,C3L-02365
0,ENSG00000000003.15,24.542658,23.397638,25.380997,24.309941,24.951679,24.027178,24.544475,26.127555,26.586320,...,24.523790,24.850667,24.850090,25.281815,24.716360,24.367574,24.012324,23.426271,24.236531,24.479784
1,ENSG00000000005.6,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,ENSG00000000419.12,25.771256,25.615764,25.432991,25.643150,26.486998,25.610305,25.577980,25.533879,25.824564,...,25.579915,25.614414,25.158160,25.598032,25.485564,25.935052,25.688440,25.748153,25.661462,25.757177
3,ENSG00000000457.14,23.769056,24.191997,23.766574,23.668907,24.444426,23.517541,23.500118,23.900951,23.641764,...,24.072407,23.924344,23.893423,23.733699,24.513004,23.333010,24.005128,23.537459,24.188776,23.635756
4,ENSG00000000460.17,17.358566,17.812061,17.617398,17.748631,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,17.756132,17.610000,17.458121,17.920082,17.107236,18.589590,18.995931,19.767101

Protein Normal:

,idx,C3N-01799,C3L-01890,C3N-00572,C3N-02423,C3N-02729,C3L-00263,C3N-01410,C3N-00578,C3N-02587,...,C3N-02582,C3L-02350,C3N-00738,C3N-00959,C3N-02003,C3N-02379,C3N-00175,C3N-01823,C3L-02549,C3L-02365
0,ENSG00000000003.15,23.367549,23.187762,23.471186,23.577705,23.285115,22.276822,23.066815,23.649865,23.736591,...,23.495219,23.326346,23.769692,23.008802,23.338255,23.538860,23.461407,23.579887,23.354698,23.223407
1,ENSG00000000005.6,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,ENSG00000000419.12,25.513388,25.522596,25.627892,25.548251,25.477157,25.609103,25.553950,25.370058,25.485570,...,25.418749,25.169371,25.305915,24.805872,25.557601,25.325738,25.517531,25.567193,25.551684,25.774110
3,ENSG00000000457.14,23.616921,23.764889,23.568230,23.800715,23.629144,24.097872,23.953650,23.529444,23.416424,...,23.763470,23.217531,23.346933,23.700347,23.417915,23.486489,23.828703,23.374495,23.494373,23.648333
4,ENSG00000000460.17,18.392785,18.044385,18.715531,18.198743,NaN,NaN,NaN,NaN,NaN,...,NaN,18.118408,18.154370,19.025523,18.065772,18.092463,18.254346,17.814889,18.020643,17.848552

Mutation:

,idx,11LU013,11LU016,11LU022,11LU035,C3L-00001,C3L-00009,C3L-00080,C3L-00093,C3L-00094,...,C3N-02423,C3N-02424,C3N-02433,C3N-02529,C3N-02572,C3N-02582,C3N-02586,C3N-02587,C3N-02588,C3N-02729
0,ENSG00000000419.12,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
1,ENSG00000000457.14,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,1,0,0,0,0
2,ENSG00000000460.17,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
3,ENSG00000000938.13,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
4,ENSG00000000971.16,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0

In [8]:
print("Mutation columns:")
print(mutation.columns[:10].tolist())

print("\nMutation first 10 rows:")
display(mutation.head(10))

Mutation columns:
['idx', '11LU013', '11LU016', '11LU022', '11LU035', 'C3L-00001', 'C3L-00009', 'C3L-00080', 'C3L-00093', 'C3L-00094']

Mutation first 10 rows:

,idx,11LU013,11LU016,11LU022,11LU035,C3L-00001,C3L-00009,C3L-00080,C3L-00093,C3L-00094,...,C3N-02423,C3N-02424,C3N-02433,C3N-02529,C3N-02572,C3N-02582,C3N-02586,C3N-02587,C3N-02588,C3N-02729
0,ENSG00000000419.12,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
1,ENSG00000000457.14,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,1,0,0,0,0
2,ENSG00000000460.17,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
3,ENSG00000000938.13,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
4,ENSG00000000971.16,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
5,ENSG00000001084.13,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
6,ENSG00000001497.16,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
7,ENSG00000001617.12,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
8,ENSG00000001626.16,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
9,ENSG00000001629.10,0,0,0,0,0,0,0,0,1,...,0,0,0,0,0,0,0,0,0,0

In [9]:
# Remove Ensembl version numbers so IDs match cleanly

rna_tumor["ensembl"] = rna_tumor["idx"].str.split(".").str[0]
rna_normal["ensembl"] = rna_normal["idx"].str.split(".").str[0]

prot_tumor["ensembl"] = prot_tumor["idx"].str.split(".").str[0]
prot_normal["ensembl"] = prot_normal["idx"].str.split(".").str[0]

mutation["ensembl"] = mutation["idx"].str.split(".").str[0]

# Check overlap across the 3 omics layers
rna_genes = set(rna_tumor["ensembl"])
prot_genes = set(prot_tumor["ensembl"])
mut_genes = set(mutation["ensembl"])

common = rna_genes & prot_genes & mut_genes

print("RNA genes:", len(rna_genes))
print("Protein genes:", len(prot_genes))
print("Mutation genes:", len(mut_genes))
print("Common genes across all 3 layers:", len(common))

RNA genes: 60624
Protein genes: 12433
Mutation genes: 10881
Common genes across all 3 layers: 6761

C:\Users\kanap\AppData\Local\Temp\ipykernel_36240\1528623314.py:3: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  rna_tumor["ensembl"] = rna_tumor["idx"].str.split(".").str[0]
C:\Users\kanap\AppData\Local\Temp\ipykernel_36240\1528623314.py:4: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  rna_normal["ensembl"] = rna_normal["idx"].str.split(".").str[0]
C:\Users\kanap\AppData\Local\Temp\ipykernel_36240\1528623314.py:6: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  prot_tumor["ensembl"] = prot_tumor["idx"].str.split(".").str[0]
C:\Users\kanap\AppData\Local\Temp\ipykernel_36240\1528623314.py:7: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  prot_normal["ensembl"] = prot_normal["idx"].str.split(".").str[0]
C:\Users\kanap\AppData\Local\Temp\ipykernel_36240\1528623314.py:9: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  mutation["ensembl"] = mutation["idx"].str.split(".").str[0]

In [10]:
# Check sample overlap between Tumor and Normal

rna_tumor_samples = set(rna_tumor.columns) - {"idx", "ensembl"}
rna_normal_samples = set(rna_normal.columns) - {"idx", "ensembl"}

prot_tumor_samples = set(prot_tumor.columns) - {"idx", "ensembl"}
prot_normal_samples = set(prot_normal.columns) - {"idx", "ensembl"}

print("RNA Tumor samples:", len(rna_tumor_samples))
print("RNA Normal samples:", len(rna_normal_samples))
print("RNA matched Tumor/Normal samples:", len(rna_tumor_samples & rna_normal_samples))

print()

print("Protein Tumor samples:", len(prot_tumor_samples))
print("Protein Normal samples:", len(prot_normal_samples))
print("Protein matched Tumor/Normal samples:", len(prot_tumor_samples & prot_normal_samples))

RNA Tumor samples: 110
RNA Normal samples: 101
RNA matched Tumor/Normal samples: 101

Protein Tumor samples: 110
Protein Normal samples: 101
Protein matched Tumor/Normal samples: 101

In [11]:
import numpy as np
from scipy import stats

# -------------------------
# RNA: paired Tumor vs Normal
# -------------------------

rna_pairs = sorted(rna_tumor_samples & rna_normal_samples)

# Collapse any duplicate Ensembl IDs after removing version numbers
rna_t = (
    rna_tumor[["ensembl"] + rna_pairs]
    .groupby("ensembl")
    .mean()
)

rna_n = (
    rna_normal[["ensembl"] + rna_pairs]
    .groupby("ensembl")
    .mean()
)

# Keep genes present in both
rna_common = rna_t.index.intersection(rna_n.index)
rna_t = rna_t.loc[rna_common]
rna_n = rna_n.loc[rna_common]

# Because the source values are already log2 transformed,
# Tumor - Normal = log2 fold change
rna_log2fc = (rna_t - rna_n).mean(axis=1)

rna_pval = stats.ttest_rel(
    rna_t.to_numpy(),
    rna_n.to_numpy(),
    axis=1,
    nan_policy="omit"
).pvalue

rna_summary = pd.DataFrame({
    "ensembl": rna_common,
    "log2fc": rna_log2fc.values,
    "pval": rna_pval
})

print("RNA summary shape:", rna_summary.shape)
display(rna_summary.head())

RNA summary shape: (60624, 3)

           ensembl    log2fc          pval
0  ENSG00000000003  0.836998  1.622058e-17
1  ENSG00000000005 -0.107327  6.117835e-01
2  ENSG00000000419  0.229971  2.443424e-06
3  ENSG00000000457  0.408261  9.268772e-16
4  ENSG00000000460  1.063954  9.084881e-31

In [12]:
# -------------------------
# Protein: paired Tumor vs Normal
# -------------------------

prot_pairs = sorted(prot_tumor_samples & prot_normal_samples)

# Collapse duplicate Ensembl IDs if any
prot_t = (
    prot_tumor[["ensembl"] + prot_pairs]
    .groupby("ensembl")
    .mean()
)

prot_n = (
    prot_normal[["ensembl"] + prot_pairs]
    .groupby("ensembl")
    .mean()
)

# Keep genes present in both datasets
prot_common = prot_t.index.intersection(prot_n.index)
prot_t = prot_t.loc[prot_common]
prot_n = prot_n.loc[prot_common]

# Paired differences
prot_diff = prot_t - prot_n

# Mean paired difference = log2 fold change
prot_log2fc = prot_diff.mean(axis=1, skipna=True)

# Number of valid matched pairs for each gene
valid_pairs = prot_diff.notna().sum(axis=1)

# Paired t-test, ignoring missing pairs
prot_pval = stats.ttest_rel(
    prot_t.to_numpy(),
    prot_n.to_numpy(),
    axis=1,
    nan_policy="omit"
).pvalue

prot_summary = pd.DataFrame({
    "ensembl": prot_common,
    "log2fc": prot_log2fc.values,
    "pval": prot_pval,
    "n_pairs": valid_pairs.values
})

print("Protein summary shape:", prot_summary.shape)

print("\nValid pair counts:")
print(prot_summary["n_pairs"].describe())

display(prot_summary.head())

Protein summary shape: (12431, 4)

Valid pair counts:
count    12431.000000
mean        83.753439
std         30.204726
min          2.000000
25%         80.500000
50%        101.000000
75%        101.000000
max        101.000000
Name: n_pairs, dtype: float64

           ensembl    log2fc          pval  n_pairs
0  ENSG00000000003  1.096470  1.189732e-30      101
1  ENSG00000000005  0.123280  6.920753e-01       12
2  ENSG00000000419  0.186768  8.045239e-09      101
3  ENSG00000000457  0.256987  2.858806e-10      101
4  ENSG00000000460  0.102737  3.012266e-01       53

In [13]:
# -------------------------
# Genomics: mutation frequency
# -------------------------

mut_sample_cols = [
    c for c in mutation.columns
    if c not in ["idx", "ensembl"]
]

# Collapse duplicate Ensembl IDs if any
mut_matrix = (
    mutation[["ensembl"] + mut_sample_cols]
    .groupby("ensembl")
    .mean()
)

# Fraction of tumors carrying a mutation in each gene
mutation_freq = mut_matrix.mean(axis=1, skipna=True)

mut_summary = pd.DataFrame({
    "ensembl": mut_matrix.index,
    "mutation_freq": mutation_freq.values
})

print("Mutation summary shape:", mut_summary.shape)

print("\nMutation frequency summary:")
print(mut_summary["mutation_freq"].describe())

print("\nTop 10 most frequently mutated genes:")
display(
    mut_summary.sort_values("mutation_freq", ascending=False).head(10)
)

Mutation summary shape: (10881, 2)

Mutation frequency summary:
count    10881.000000
mean         0.021636
std          0.022277
min          0.009259
25%          0.009259
50%          0.018519
75%          0.027778
max          0.592593
Name: mutation_freq, dtype: float64

Top 10 most frequently mutated genes:

              ensembl  mutation_freq
4588  ENSG00000141510       0.592593
5628  ENSG00000155657       0.361111
5017  ENSG00000146648       0.361111
7030  ENSG00000168702       0.351852
9654  ENSG00000198626       0.333333
6513  ENSG00000164796       0.333333
8296  ENSG00000181143       0.333333
3817  ENSG00000133703       0.324074
353   ENSG00000042781       0.296296
1170  ENSG00000091656       0.250000

In [14]:
# Rename columns before merging so nothing collides

rna_final = rna_summary.rename(columns={
    "log2fc": "rna_log2fc",
    "pval": "rna_pval"
})

prot_final = prot_summary.rename(columns={
    "log2fc": "prot_log2fc",
    "pval": "prot_pval"
})

# Merge RNA + protein + mutation
merged = (
    rna_final
    .merge(prot_final, on="ensembl", how="inner")
    .merge(mut_summary, on="ensembl", how="inner")
)

print("Genes surviving all 3 layers:", merged.shape[0])

display(merged.head())

Genes surviving all 3 layers: 6760

,ensembl,rna_log2fc,rna_pval,prot_log2fc,prot_pval,n_pairs,mutation_freq
0,ENSG00000000419,0.229971,2.443424e-06,0.186768,8.045239e-09,101,0.009259
1,ENSG00000000457,0.408261,9.268772e-16,0.256987,2.858806e-10,101,0.009259
2,ENSG00000000460,1.063954,9.084881e-31,0.102737,3.012266e-01,53,0.009259
3,ENSG00000000938,-1.884782,3.154438e-46,-0.585544,3.892596e-24,101,0.018519
4,ENSG00000000971,-0.181050,1.840694e-02,-0.683658,3.402547e-26,101,0.037037

In [15]:
%pip install mygene -q

Note: you may need to restart the kernel to use updated packages.

In [16]:
import mygene
import pandas as pd

mg = mygene.MyGeneInfo()

results = mg.querymany(
    merged["ensembl"].tolist(),
    scopes="ensembl.gene",
    fields="symbol",
    species="human"
)

mapping = pd.DataFrame([
    {
        "ensembl": x.get("query"),
        "gene": x.get("symbol")
    }
    for x in results
    if x.get("symbol") is not None
])

mapping = mapping.drop_duplicates(subset="ensembl")

print("Ensembl IDs submitted:", len(merged))
print("Successfully mapped:", len(mapping))

display(mapping.head(10))

1 input query terms found no hit:	['ENSG00000130723']

Ensembl IDs submitted: 6760
Successfully mapped: 6758

           ensembl    gene
0  ENSG00000000419    DPM1
1  ENSG00000000457   SCYL3
2  ENSG00000000460   FIRRM
3  ENSG00000000938     FGR
4  ENSG00000000971     CFH
5  ENSG00000001084    GCLC
6  ENSG00000001497   LAS1L
7  ENSG00000001617  SEMA3F
8  ENSG00000001626    CFTR
9  ENSG00000001629  ANKIB1

In [18]:
merged_genes = merged.merge(mapping, on="ensembl", how="inner")

print("Genes after symbol mapping:", len(merged_genes))
print("Duplicate gene symbols:", merged_genes["gene"].duplicated().sum())

display(
    merged_genes[
        [
            "gene",
            "ensembl",
            "rna_log2fc",
            "rna_pval",
            "prot_log2fc",
            "prot_pval",
            "mutation_freq",
            "n_pairs"
        ]
    ].head(10)
)

Genes after symbol mapping: 6758
Duplicate gene symbols: 0

,gene,ensembl,rna_log2fc,rna_pval,prot_log2fc,prot_pval,mutation_freq,n_pairs
0,DPM1,ENSG00000000419,0.229971,2.443424e-06,0.186768,8.045239e-09,0.009259,101
1,SCYL3,ENSG00000000457,0.408261,9.268772e-16,0.256987,2.858806e-10,0.009259,101
2,FIRRM,ENSG00000000460,1.063954,9.084881e-31,0.102737,3.012266e-01,0.009259,53
3,FGR,ENSG00000000938,-1.884782,3.154438e-46,-0.585544,3.892596e-24,0.018519,101
4,CFH,ENSG00000000971,-0.181050,1.840694e-02,-0.683658,3.402547e-26,0.037037,101
5,GCLC,ENSG00000001084,0.441356,4.729964e-04,-0.551105,7.195283e-14,0.009259,101
6,LAS1L,ENSG00000001497,0.330267,1.638164e-15,0.372646,8.267604e-29,0.009259,101
7,SEMA3F,ENSG00000001617,-0.670189,1.115769e-11,-0.529300,4.816679e-14,0.009259,80
8,CFTR,ENSG00000001626,-1.541377,4.779188e-11,-0.998275,9.012070e-07,0.018519,55
9,ANKIB1,ENSG00000001629,0.438844,1.246133e-21,-0.087236,8.395133e-06,0.027778,101

In [19]:
import numpy as np

df = merged_genes.copy()

# 1. RNA vs protein direction agreement
df["concordant"] = (
    np.sign(df["rna_log2fc"]) ==
    np.sign(df["prot_log2fc"])
)

# 2. Evidence magnitude for each layer
df["transcriptomic"] = df["rna_log2fc"].abs()
df["proteomic"] = df["prot_log2fc"].abs()
df["genomic"] = df["mutation_freq"]

# 3. Rank-normalize each layer to 0–1
df["tx_rank"] = df["transcriptomic"].rank(pct=True)
df["prot_rank"] = df["proteomic"].rank(pct=True)
df["gen_rank"] = df["genomic"].rank(pct=True)

# 4. Equal-weight multi-evidence score
df["score"] = (
    df["tx_rank"] +
    df["prot_rank"] +
    df["gen_rank"]
) / 3

# 5. Rank highest to lowest
ranked_luad = df.sort_values("score", ascending=False).reset_index(drop=True)

print("Genes scored:", len(ranked_luad))
print("Concordant genes:", ranked_luad["concordant"].sum())
print("Discordant genes:", (~ranked_luad["concordant"]).sum())

display(
    ranked_luad[
        [
            "gene",
            "rna_log2fc",
            "rna_pval",
            "prot_log2fc",
            "prot_pval",
            "mutation_freq",
            "n_pairs",
            "concordant",
            "score"
        ]
    ].head(15)
)

Genes scored: 6758
Concordant genes: 4918
Discordant genes: 1840

,gene,rna_log2fc,rna_pval,prot_log2fc,prot_pval,mutation_freq,n_pairs,concordant,score
0,ACTN2,-3.447004,4.799384e-51,-1.730805,8.882219e-63,0.120370,101,True,0.992157
1,ZNF536,-2.715979,3.992167e-31,2.711760,6.376380e-05,0.120370,15,False,0.987570
2,COL6A6,-3.042473,3.613502e-45,-1.885465,2.642027e-52,0.083333,101,True,0.985918
3,TNR,-3.762747,6.267168e-36,-1.266200,1.802563e-30,0.111111,97,True,0.985005
4,SCN7A,-2.936123,4.000878e-39,-1.406593,2.899179e-45,0.092593,101,True,0.982367
5,ABCA8,-3.256992,6.276034e-48,-1.580883,3.469584e-55,0.055556,101,True,0.975782
6,ADAMTS16,2.558142,4.323997e-26,1.233881,3.375016e-08,0.101852,46,True,0.972650
7,TNXB,-2.951528,2.586049e-43,-1.455977,7.240442e-47,0.055556,101,True,0.972181
8,NOS1,-3.691042,1.947635e-36,-1.069219,3.994112e-24,0.074074,101,True,0.971811
9,MYH2,-2.726163,1.727734e-32,-1.611129,2.757223e-02,0.055556,12,True,0.970849
10,MASP1,-3.403353,1.385034e-52,-1.134725,6.123315e-48,0.064815,101,True,0.970233
11,ERICH3,-3.340330,5.838046e-24,-0.988712,3.216091e-19,0.092593,101,True,0.969493
12,COL11A1,6.156878,3.844462e-41,0.870645,1.419048e-15,0.203704,96,True,0.968137
13,SEMA5A,-2.430893,1.188043e-49,-1.096353,4.064396e-20,0.120370,89,True,0.967150
14,GDF10,-3.710243,1.212992e-43,-1.354044,1.330616e-35,0.046296,97,True,0.966607

In [20]:
# Add overall rank
ranked_luad["rank"] = ranked_luad.index + 1

# Check established LUAD-related genes
known_luad = [
    "TP53", "KRAS", "EGFR", "STK11",
    "KEAP1", "BRAF", "MET", "ERBB2",
    "ALK", "NF1"
]

known_hits = ranked_luad[
    ranked_luad["gene"].isin(known_luad)
][
    [
        "rank",
        "gene",
        "rna_log2fc",
        "prot_log2fc",
        "mutation_freq",
        "n_pairs",
        "concordant",
        "score"
    ]
]

display(known_hits.sort_values("rank"))

,rank,gene,rna_log2fc,prot_log2fc,mutation_freq,n_pairs,concordant,score
571,572,TP53,0.598210,0.504204,0.592593,83,True,0.792148
1319,1320,MET,0.754090,0.459299,0.018519,101,True,0.677913
1623,1624,KRAS,0.344291,-0.276264,0.324074,101,False,0.643632
1799,1800,ALK,-0.481036,0.181580,0.074074,20,False,0.625062
1806,1807,EGFR,0.401336,0.203822,0.361111,101,True,0.623829
2749,2750,ERBB2,0.923188,0.360327,0.009259,101,True,0.538177
2903,2904,STK11,0.005949,-0.334504,0.166667,97,False,0.526117
2924,2925,NF1,0.399426,-0.047639,0.101852,101,False,0.524785
3110,3111,KEAP1,0.194928,-0.145442,0.101852,101,False,0.510284
3885,3886,BRAF,-0.184798,-0.066437,0.064815,101,True,0.448431

In [21]:
print("Top 15 protein coverage:")
display(
    ranked_luad[
        ["rank", "gene", "n_pairs", "score"]
    ].head(15)
)

Top 15 protein coverage:

    rank      gene  n_pairs     score
0      1     ACTN2      101  0.992157
1      2    ZNF536       15  0.987570
2      3    COL6A6      101  0.985918
3      4       TNR       97  0.985005
4      5     SCN7A      101  0.982367
5      6     ABCA8      101  0.975782
6      7  ADAMTS16       46  0.972650
7      8      TNXB      101  0.972181
8      9      NOS1      101  0.971811
9     10      MYH2       12  0.970849
10    11     MASP1      101  0.970233
11    12    ERICH3      101  0.969493
12    13   COL11A1       96  0.968137
13    14    SEMA5A       89  0.967150
14    15     GDF10       97  0.966607

In [22]:
# QC filter: require protein measurements in at least 50 matched pairs
df_qc = merged_genes[merged_genes["n_pairs"] >= 50].copy()

# Concordance
df_qc["concordant"] = (
    np.sign(df_qc["rna_log2fc"]) ==
    np.sign(df_qc["prot_log2fc"])
)

# Evidence magnitudes
df_qc["transcriptomic"] = df_qc["rna_log2fc"].abs()
df_qc["proteomic"] = df_qc["prot_log2fc"].abs()
df_qc["genomic"] = df_qc["mutation_freq"]

# Normalize each layer
df_qc["tx_rank"] = df_qc["transcriptomic"].rank(pct=True)
df_qc["prot_rank"] = df_qc["proteomic"].rank(pct=True)
df_qc["gen_rank"] = df_qc["genomic"].rank(pct=True)

# Equal weights
df_qc["score"] = (
    df_qc["tx_rank"] +
    df_qc["prot_rank"] +
    df_qc["gen_rank"]
) / 3

# Final ranking
ranked_luad_qc = (
    df_qc
    .sort_values("score", ascending=False)
    .reset_index(drop=True)
)

ranked_luad_qc["rank"] = ranked_luad_qc.index + 1

print("Genes before QC:", len(merged_genes))
print("Genes after QC:", len(ranked_luad_qc))

display(
    ranked_luad_qc[
        [
            "rank", "gene",
            "rna_log2fc", "rna_pval",
            "prot_log2fc", "prot_pval",
            "mutation_freq", "n_pairs",
            "concordant", "score"
        ]
    ].head(15)
)

Genes before QC: 6758
Genes after QC: 5533

,rank,gene,rna_log2fc,rna_pval,prot_log2fc,prot_pval,mutation_freq,n_pairs,concordant,score
0,1,ACTN2,-3.447004,4.799384e-51,-1.730805,8.882219e-63,0.120370,101,True,0.993373
1,2,COL6A6,-3.042473,3.613502e-45,-1.885465,2.642027e-52,0.083333,101,True,0.988403
2,3,TNR,-3.762747,6.267168e-36,-1.266200,1.802563e-30,0.111111,97,True,0.986324
3,4,SCN7A,-2.936123,4.000878e-39,-1.406593,2.899179e-45,0.092593,101,True,0.984818
4,5,ABCA8,-3.256992,6.276034e-48,-1.580883,3.469584e-55,0.055556,101,True,0.978553
5,6,TNXB,-2.951528,2.586049e-43,-1.455977,7.240442e-47,0.055556,101,True,0.975420
6,7,NOS1,-3.691042,1.947635e-36,-1.069219,3.994112e-24,0.074074,101,True,0.974667
7,8,MASP1,-3.403353,1.385034e-52,-1.134725,6.123315e-48,0.064815,101,True,0.973101
8,9,ERICH3,-3.340330,5.838046e-24,-0.988712,3.216091e-19,0.092593,101,True,0.972649
9,10,SEMA5A,-2.430893,1.188043e-49,-1.096353,4.064396e-20,0.120370,89,True,0.971203
10,11,COL11A1,6.156878,3.844462e-41,0.870645,1.419048e-15,0.203704,96,True,0.970842
11,12,ITIH5,-2.337581,4.382869e-39,-1.341845,8.524014e-52,0.064815,101,True,0.969366
12,13,COL3A1,2.790799,3.659591e-33,0.971055,2.822343e-26,0.111111,101,True,0.969275
13,14,GDF10,-3.710243,1.212992e-43,-1.354044,1.330616e-35,0.046296,97,True,0.969275
14,15,CALCRL,-2.810884,4.491392e-55,-1.772676,1.082163e-50,0.046296,101,True,0.968974

In [23]:
known_luad = [
    "TP53", "KRAS", "EGFR", "STK11",
    "KEAP1", "BRAF", "MET", "ERBB2",
    "ALK", "NF1"
]

display(
    ranked_luad_qc[
        ranked_luad_qc["gene"].isin(known_luad)
    ][
        ["rank", "gene", "rna_log2fc", "prot_log2fc",
         "mutation_freq", "n_pairs", "concordant", "score"]
    ].sort_values("rank")
)

,rank,gene,rna_log2fc,prot_log2fc,mutation_freq,n_pairs,concordant,score
423,424,TP53,0.598210,0.504204,0.592593,83,True,0.808181
947,948,MET,0.754090,0.459299,0.018519,101,True,0.698084
1228,1229,KRAS,0.344291,-0.276264,0.324074,101,False,0.658353
1375,1376,EGFR,0.401336,0.203822,0.361111,101,True,0.638141
2037,2038,ERBB2,0.923188,0.360327,0.009259,101,True,0.558347
2274,2275,NF1,0.399426,-0.047639,0.101852,101,False,0.535364
2281,2282,STK11,0.005949,-0.334504,0.166667,97,False,0.534791
2422,2423,KEAP1,0.194928,-0.145442,0.101852,101,False,0.520061
3081,3082,BRAF,-0.184798,-0.066437,0.064815,101,True,0.455901

In [24]:
# Final top 15 target table

targets_luad = ranked_luad_qc[
    [
        "rank",
        "gene",
        "ensembl",
        "rna_log2fc",
        "rna_pval",
        "prot_log2fc",
        "prot_pval",
        "mutation_freq",
        "n_pairs",
        "concordant",
        "score"
    ]
].head(15).copy()

output_file = Path("targets_luad.csv")

targets_luad.to_csv(output_file, index=False)

print("Saved:", output_file.resolve())
display(targets_luad)

Saved: C:\Users\kanap\OneDrive\Desktop\biot6900\targets_luad.csv

,rank,gene,ensembl,rna_log2fc,rna_pval,prot_log2fc,prot_pval,mutation_freq,n_pairs,concordant,score
0,1,ACTN2,ENSG00000077522,-3.447004,4.799384e-51,-1.730805,8.882219e-63,0.120370,101,True,0.993373
1,2,COL6A6,ENSG00000206384,-3.042473,3.613502e-45,-1.885465,2.642027e-52,0.083333,101,True,0.988403
2,3,TNR,ENSG00000116147,-3.762747,6.267168e-36,-1.266200,1.802563e-30,0.111111,97,True,0.986324
3,4,SCN7A,ENSG00000136546,-2.936123,4.000878e-39,-1.406593,2.899179e-45,0.092593,101,True,0.984818
4,5,ABCA8,ENSG00000141338,-3.256992,6.276034e-48,-1.580883,3.469584e-55,0.055556,101,True,0.978553
5,6,TNXB,ENSG00000168477,-2.951528,2.586049e-43,-1.455977,7.240442e-47,0.055556,101,True,0.975420
6,7,NOS1,ENSG00000089250,-3.691042,1.947635e-36,-1.069219,3.994112e-24,0.074074,101,True,0.974667
7,8,MASP1,ENSG00000127241,-3.403353,1.385034e-52,-1.134725,6.123315e-48,0.064815,101,True,0.973101
8,9,ERICH3,ENSG00000178965,-3.340330,5.838046e-24,-0.988712,3.216091e-19,0.092593,101,True,0.972649
9,10,SEMA5A,ENSG00000112902,-2.430893,1.188043e-49,-1.096353,4.064396e-20,0.120370,89,True,0.971203
10,11,COL11A1,ENSG00000060718,6.156878,3.844462e-41,0.870645,1.419048e-15,0.203704,96,True,0.970842
11,12,ITIH5,ENSG00000123243,-2.337581,4.382869e-39,-1.341845,8.524014e-52,0.064815,101,True,0.969366
12,13,COL3A1,ENSG00000168542,2.790799,3.659591e-33,0.971055,2.822343e-26,0.111111,101,True,0.969275
13,14,GDF10,ENSG00000266524,-3.710243,1.212992e-43,-1.354044,1.330616e-35,0.046296,97,True,0.969275
14,15,CALCRL,ENSG00000064989,-2.810884,4.491392e-55,-1.772676,1.082163e-50,0.046296,101,True,0.968974

In [25]:
discordant_hits = ranked_luad_qc[
    ranked_luad_qc["concordant"] == False
][
    [
        "rank",
        "gene",
        "rna_log2fc",
        "rna_pval",
        "prot_log2fc",
        "prot_pval",
        "mutation_freq",
        "n_pairs",
        "score"
    ]
].head(10)

print("Highest-ranked discordant genes:")
display(discordant_hits)

Highest-ranked discordant genes:

,rank,gene,rna_log2fc,rna_pval,prot_log2fc,prot_pval,mutation_freq,n_pairs,score
26,27,SPTB,2.114807,8.150418e-15,-1.544332,4.582166e-43,0.046296,101,0.956684
34,35,POTEF,2.430080,1.711076e-09,-1.160909,1.481158e-45,0.046296,101,0.952889
55,56,GRM7,-1.344597,4.901506e-10,1.058962,9.673363e-17,0.101852,73,0.938219
122,123,SERPINA4,2.711752,2.819468e-17,-0.995482,2.446229e-43,0.027778,101,0.909151
131,132,BGN,0.968628,9.886628e-19,-1.331416,1.152213e-51,0.046296,101,0.906380
144,145,F5,0.839469,1.821624e-08,-1.047533,3.025712e-33,0.092593,101,0.901440
163,164,COL18A1,1.289708,9.214376e-30,-0.897126,4.646176e-46,0.037037,101,0.893277
173,174,COL6A3,1.103085,1.893319e-18,-0.651289,3.634741e-27,0.064815,101,0.885023
188,189,AGRN,0.894073,8.056355e-21,-1.109901,5.569676e-43,0.037037,101,0.878396
198,199,BRCA2,0.899466,3.211683e-21,-0.675165,3.425500e-16,0.074074,60,0.874902